behaviors:
  # UnitBox:
  #   trainer_type: ppo
  #   hyperparameters:
  #     batch_size: 2048
  #     buffer_size: 20480
  #     learning_rate: 0.0003
  #     beta: 0.005
  #     epsilon: 0.2
  #     lambd: 0.95
  #     num_epoch: 3
  #     learning_rate_schedule: linear
  #   network_settings:
  #     normalize: true
  #     hidden_units: 512
  #     num_layers: 3
  #     vis_encode_type: simple
  #   reward_signals:
  #     extrinsic:
  #       gamma: 0.995
  #       strength: 1.0
  #   keep_checkpoints: 5
  #   max_steps: 30000000
  #   time_horizon: 1000
  #   summary_freq: 30000
  RegularBox:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 4096
      learning_rate: 0.001
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 30000000
    time_horizon: 2048
    summary_freq: 5000

  
  # Add this section
environment_parameters:
  # unit_box:
  #   curriculum:
  #     - name: MyFirstLesson # The '-' is important as this is a list
  #       completion_criteria:
  #         measure: reward
  #         behavior: UnitBox
  #         signal_smoothing: true
  #         min_lesson_length: 100
  #         threshold: 100.0
  #       value: 1.0
  #     - name: MySecondLesson # This is the start of the second lesson
  #       completion_criteria:
  #         measure: reward
  #         behavior: UnitBox
  #         signal_smoothing: true
  #         min_lesson_length: 100
  #         threshold: 0.6
  #         require_reset: true
  #       value: 2.0
  #     - name: MyLastLesson
  #       value: 3.0
  regular_box:
    curriculum:
      - name: MyFirstLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: RegularBox
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1000
        value: 0.0
      - name: MySecondLesson # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: RegularBox
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.6
          require_reset: true
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 4.0
            max_value: 7.0
      - name: MyLastLesson
        value: 8.0
